# Generated by Django 5.1.1 on 2024-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='İnfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(verbose_name='Məlumat')),
            ],
            options={
                'verbose_name': 'Məlumat',
                'verbose_name_plural': 'Məlumat',
            },
        ),
    ]
