# Generated by Django 5.1.1 on 2024-09-24 11:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_i_nfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nfo',
            name='txt',
            field=ckeditor.fields.RichTextField(verbose_name='Məlumat'),
        ),
    ]
